var keyModes = {"T001":{"calculate":"sum","title":"Total Population"},
"T002":{"calculate":"reaverage","title":"Population Density"},
"T004":{"calculate":"sum","title":"Gender"},
"T007":{"calculate":"sum","title":"Age Groups"},
"T013":{"calculate":"sum","title":"Race"},
"T150":{"calculate":"sum","title":"Education"},
"T037":{"calculate":"sum","title":"Employeement"},
"T049":{"calculate":"sum","title":"Industry"},
"T050":{"calculate":"sum","title":"Profession"},
"T053":{"calculate":"sum","title":"Job Sector"},
"T056":{"calculate":"sum","title":"Household Income"},
"T094":{"calculate":"sum","title":"Rent or Own"},
"T219":{"calculate":"sum","title":"Renter Length of Stay"},
"T197":{"calculate":"sum","title":"Number of Bedrooms in Rental Housing"},
"T128":{"calculate":"sum","title":"Transportation"},
"T129":{"calculate":"sum","title":"Length of Commute"},
"T133":{"calculate":"sum","title":"Citizenship"},
"T134":{"calculate":"sum","title":"Immigration"},
"T139":{"calculate":"unique","title":"Place of Birth"},
"C16001":{"calculate":"unique","title":"Household Language"}
}